# Generated by Django 2.2.5 on 2020-02-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Appeared at'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='disappear_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Disappear at'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.Pokemon'),
        ),
    ]
