# Generated by Django 2.2.5 on 2020-02-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20200205_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='appeared_at',
            new_name='appeared_att',
        ),
    ]
