# Generated by Django 2.2.5 on 2020-02-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20200211_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon_elements/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название стихии'),
        ),
    ]
